version: "3.8"

services:
  redis:
    image: redis:6.0.4-alpine
    ports:
      - "6379:6379"
    networks:
      - web
    command: redis-server --port 6379
  db:
    image: postgres:11.8
    networks:
      - web
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    networks:
      - web
    #command: "node build/main"
    environment:
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_URL: ${TYPEORM_URL}
      SECRET_KEY: ${SECRET_KEY}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_CLIENT_URL: ${GITHUB_CLIENT_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_URL: ${GOOGLE_CLIENT_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      TYPEORM_MIGRATIONS: /build/migrations/*.js
      TYPEORM_ENTITIES: /build/models/*.js
networks:
  web:
